# Pandas — Exploração dos dados

In [1]:
import pandas as pd
# Importa a biblioteca pandas e apelida como 'pd' para ficar mais fácil

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")
# Carrega os dados do arquivo CSV diretamente de uma URL para um DataFrame com o nome 'df'.

In [3]:
df.head(10)
# Exibe as 10 primeiras linhas do df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M
5,2025.0,EN,FT,Data Engineer,80000,USD,80000,US,0,US,M
6,2025.0,SE,FT,Data Scientist,185000,USD,185000,US,0,US,M
7,2025.0,SE,FT,Data Scientist,148000,USD,148000,US,0,US,M
8,2025.0,MI,FT,Data Scientist,135000,USD,135000,CA,0,CA,M
9,2025.0,MI,FT,Data Scientist,108000,USD,108000,CA,0,CA,M

In [4]:
df.info()
# Exibe resumo do df, inclui: tipo de dados, contagem de não-nulos e uso de memória

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [5]:
df.describe()
# Exibe estatísticas descritivas das colunas numéricas do DataFrame, como média, desvio padrão, mínimo, máximo e quartis.

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [6]:
df.shape
# Exibe as dimensões do df (numero de linhas e colunas)

(133349, 11)

In [7]:
linhas, colunas = df.shape[0], df.shape[1]
print ("Nº Linhas:", linhas)
print ("Nº Colunas:", colunas)

# Extrai o numero de linhas e colunas do df.

Nº Linhas: 133349
Nº Colunas: 11

In [8]:
df.columns
# Exibe os nomes das colunas do df

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [9]:
#Dicionário de mapeamento das colunas de inglês para português
colunas_pt = {
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'tipoEmprego',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'salario_usd',
    'employee_residence': 'paisFunc',
    'remote_ratio': 'txRemoto',
    'company_location': 'paisEmpresa',
    'company_size': 'porte'
}

# Renomeia as colunas do df
df.rename(columns=colunas_pt, inplace=True)

# Exibe as novas colunas
df.columns

Index(['ano', 'senioridade', 'tipoEmprego', 'cargo', 'salario', 'moeda',
       'salario_usd', 'paisFunc', 'txRemoto', 'paisEmpresa', 'porte'],
      dtype='object')

In [10]:
df['senioridade'].value_counts()
# Conta a frequência de cada valor único na coluna 'senioridade'

senioridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [11]:
# Substitui os valores na coluna 'senioridade'
df['senioridade'] = df['senioridade'].replace({
    'MI': 'Pleno',
    'SE': 'Sênior',
    'EN': 'Júnior',
    'EX': 'Executivo'
})

df['senioridade'].value_counts()

senioridade
Sênior       77241
Pleno        40465
Júnior       12443
Executivo     3200
Name: count, dtype: int64

In [12]:
df['tipoEmprego'] = df['tipoEmprego'].replace({
    'FT': 'Tempo Integral',
    'CT': 'Contrato',
    'PT': 'Tempo Parcial',
    'FL': 'Freelance'
})

df['tipoEmprego'].value_counts()

tipoEmprego
Tempo Integral    132563
Contrato             394
Tempo Parcial        376
Freelance             16
Name: count, dtype: int64

In [13]:
df['porte'] = df['porte'].replace({
    'M': 'Médio',
    'L': 'Grande',
    'S': 'Pequeno'
})

df['porte'].value_counts()

porte
Médio      129561
Grande       3574
Pequeno       214
Name: count, dtype: int64

In [14]:
df['txRemoto'] = df['txRemoto'].replace({
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
})

df['txRemoto'].value_counts()

txRemoto
Presencial    105312
Remoto         27718
Híbrido          319
Name: count, dtype: int64

In [15]:
df.head()

,ano,senioridade,tipoEmprego,cargo,salario,moeda,salario_usd,paisFunc,txRemoto,paisEmpresa,porte
0,2025.0,Sênior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Médio
1,2025.0,Sênior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Médio
2,2025.0,Pleno,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Médio
3,2025.0,Pleno,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Médio
4,2025.0,Júnior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Médio

In [16]:
df.describe(include="object")
# Exibe as estatísticas descritivas das colunas não numéricas, como contagem, valores únicos, valor mais frequente e sua frequência.

,senioridade,tipoEmprego,cargo,moeda,paisFunc,txRemoto,paisEmpresa,porte
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Sênior,Tempo Integral,Data Scientist,USD,US,Presencial,US,Médio
freq,77241,132563,17314,126140,119579,105312,119641,129561

In [17]:
df.isnull()
# Verifica se há valores nulos em cada célula do df

,ano,senioridade,tipoEmprego,cargo,salario,moeda,salario_usd,paisFunc,txRemoto,paisEmpresa,porte
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
133344,False,False,False,False,False,False,False,False,False,False,False
133345,False,False,False,False,False,False,False,False,False,False,False
133346,False,False,False,False,False,False,False,False,False,False,False
133347,False,False,False,False,False,False,False,False,False,False,False
133348,False,False,False,False,False,False,False,False,False,False,False

In [18]:
df.isnull().sum()
# Calcula a soma dos valores nulos em cada coluna do df

ano            10
senioridade     0
tipoEmprego     0
cargo           0
salario         0
moeda           0
salario_usd     0
paisFunc        0
txRemoto        0
paisEmpresa     0
porte           0
dtype: int64

In [19]:
df['ano'].unique()
# exibe os valores únicos presentes na coluna 'ano' do df

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [20]:
df[df.isnull().any(axis=1)]
# Filtre o df e exibe apenas linhas com pelo menos um valor nulo

,ano,senioridade,tipoEmprego,cargo,salario,moeda,salario_usd,paisFunc,txRemoto,paisEmpresa,porte
5588,NaN,Sênior,Tempo Integral,Product Manager,184500,USD,184500,US,Presencial,US,Médio
59692,NaN,Pleno,Tempo Integral,Engineer,110000,USD,110000,DE,Presencial,DE,Médio
59710,NaN,Júnior,Tempo Integral,Data Scientist,208800,USD,208800,US,Presencial,US,Médio
59759,NaN,Sênior,Tempo Integral,Software Engineer,135000,USD,135000,US,Presencial,US,Médio
59789,NaN,Sênior,Tempo Integral,Engineer,112000,USD,112000,US,Presencial,US,Médio
131000,NaN,Sênior,Tempo Integral,Machine Learning Engineer,163800,USD,163800,US,Presencial,US,Médio
131006,NaN,Sênior,Tempo Integral,Data Analytics Manager,204500,USD,204500,US,Presencial,US,Médio
133054,NaN,Júnior,Tempo Integral,Data Scientist,40000,USD,40000,JP,Remoto,MY,Grande
133281,NaN,Pleno,Tempo Integral,Machine Learning Engineer,180000,PLN,46597,PL,Remoto,PL,Grande
133317,NaN,Pleno,Tempo Integral,Data Scientist,130000,USD,130000,US,Híbrido,US,Grande

# Pandas — Tratamento de valores nulos

In [21]:
import numpy as np

In [22]:
df_salarios = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniele'],
    'salario': [4000, np.nan, 5000, np.nan]
})
# Cria um df do pandas chamado 'df_salarios'

In [23]:
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))
# Preenche os valores nulos da coluna 'salario' usando a média dos salários existentes

In [24]:
df_salarios['salario_mediana'] =df_salarios['salario'].fillna(df_salarios['salario'].median())

In [25]:
df_salarios

      nome  salario  salario_media  salario_mediana
0      Ana   4000.0         4000.0           4000.0
1    Bruno      NaN         4500.0           4500.0
2   Carlos   5000.0         5000.0           5000.0
3  Daniele      NaN         4500.0           4500.0

In [26]:
df_temperaturas = pd.DataFrame({
    'Dia': ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'],
    'Temperatura':[30, np.nan, np.nan, 28, 27]
})

In [27]:
df_temperaturas['Preenchido_ffill'] = df_temperaturas['Temperatura'].ffill()
# Preenche os dados nulos da coluna temperatura com o último valor lido

In [28]:
df_temperaturas

       Dia  Temperatura  Preenchido_ffill
0  Segunda         30.0              30.0
1    Terça          NaN              30.0
2   Quarta          NaN              30.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0

In [31]:
df_temperaturas['Preenchido_bfill'] = df_temperaturas['Temperatura'].bfill()
# preenche os valores nulos com o próximo valor válido lido

df_temperaturas

       Dia  Temperatura  Preenchido_ffill  Preenchido_bfill
0  Segunda         30.0              30.0              30.0
1    Terça          NaN              30.0              28.0
2   Quarta          NaN              30.0              28.0
3   Quinta         28.0              28.0              28.0
4    Sexta         27.0              27.0              27.0

In [33]:
df_cidades = pd.DataFrame({
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Daniele', 'Higor'],
    'Cidade': ['São Paulo', np.nan, 'Barcelona', np.nan, 'Viseu']
})

In [35]:
df_cidades['cidade_preenchida'] = df_cidades['Cidade'].fillna('Não Informado')
# Irá substituir os valores nulos pela mensagem "Não Informado"

df_cidades

      Nome     Cidade cidade_preenchida
0      Ana  São Paulo         São Paulo
1    Bruno        NaN     Não Informado
2   Carlos  Barcelona         Barcelona
3  Daniele        NaN     Não Informado
4    Higor      Viseu             Viseu

In [37]:
df_limpo = df.dropna()
# Remove as linhas do df que tem pelo menos um valor nulo e armazena o df com linhas completas na variável 'df_limpo'

In [40]:
df_limpo.isnull().sum()
# Soma os valores nulos em cada coluna do df 'df_limpo'.

ano            0
senioridade    0
tipoEmprego    0
cargo          0
salario        0
moeda          0
salario_usd    0
paisFunc       0
txRemoto       0
paisEmpresa    0
porte          0
dtype: int64

In [41]:
df_limpo.head()
# Retorna as 5 primeiras linhas do 'df_limpo'

,ano,senioridade,tipoEmprego,cargo,salario,moeda,salario_usd,paisFunc,txRemoto,paisEmpresa,porte
0,2025.0,Sênior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Médio
1,2025.0,Sênior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Médio
2,2025.0,Pleno,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Médio
3,2025.0,Pleno,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Médio
4,2025.0,Júnior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Médio

In [42]:
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   ano          133339 non-null  float64
 1   senioridade  133339 non-null  object
 2   tipoEmprego  133339 non-null  object
 3   cargo        133339 non-null  object
 4   salario      133339 non-null  int64
 5   moeda        133339 non-null  object
 6   salario_usd  133339 non-null  int64
 7   paisFunc     133339 non-null  object
 8   txRemoto     133339 non-null  object
 9   paisEmpresa  133339 non-null  object
 10  porte        133339 non-null  object
dtypes: float64(1), int64(2), object(8)
memory usage: 12.2+ MB

In [44]:
df_limpo = df_limpo.assign(ano = df_limpo['ano'].astype('int64'))
# Converte a coluna 'ano' do 'df_limpo para tipo int64

In [45]:
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   ano          133339 non-null  int64
 1   senioridade  133339 non-null  object
 2   tipoEmprego  133339 non-null  object
 3   cargo        133339 non-null  object
 4   salario      133339 non-null  int64
 5   moeda        133339 non-null  object
 6   salario_usd  133339 non-null  int64
 7   paisFunc     133339 non-null  object
 8   txRemoto     133339 non-null  object
 9   paisEmpresa  133339 non-null  object
 10  porte        133339 non-null  object
dtypes: int64(3), object(8)
memory usage: 12.2+ MB